# Generated by Django 4.0.1 on 2022-01-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification',
            old_name='checking',
            new_name='verify',
        ),
    ]
